# Generated by Django 5.2.3 on 2025-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixithubapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='example', max_length=150),
            preserve_default=False,
        ),
    ]
